CREATE TABLE IF NOT EXISTS cms_pages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL,
    content TEXT,
    created_at DATETIME,
    updated_at DATETIME,
    image TEXT,
    cat TEXT DEFAULT 'page',
    tag TEXT,
    template_slug VARCHAR(255) DEFAULT NULL,
    meta_description TEXT,
    meta_keywords TEXT,
    content_format TEXT DEFAULT 'html',
    canonical_url TEXT,
    schema_type TEXT,
    schema_data TEXT,
    FOREIGN KEY(user_id) REFERENCES users(id),
    UNIQUE(slug)
);
